- name: Kill existing node_exporter process
  shell: "pkill -f node_exporter || true"

- name: Start node_exporter
  shell: "/usr/local/node_exporter/node_exporter &"
  args:
    chdir: /usr/local/node_exporter/

- name: Kill existing process-exporter process
  shell: "pkill -f process-exporter || true"

- name: Start process-exporter
  shell: "/usr/local/process-exporter/process-exporter -config.path /usr/local/process-exporter/process_name.yml &"
  args:
    chdir: /usr/local/process-exporter/

- name: Kill existing grok_exporter process
  shell: "pkill -f grok_exporter || true"

- name: Start grok_exporter
  shell: "./grok_exporter -config ./example/config.yml &"
  args:
    chdir: /usr/local/grok_exporter/
