global:
  config_version: 3

input:
  type: file
  path: /logs/f2pool.log
  readall: false # 从文件末尾开始读取

imports:
  - type: grok_patterns
    dir: ./patterns

grok_patterns:
  - 'PROVER_LOG perf: %{NUMBER:total_perf} \(1m: %{NUMBER:proof1m} P\/s, 5m: %{NUMBER:proof5m} P\/s, 30m: %{NUMBER:proof30m} P\/s, 60m: %{NUMBER:proof60m} P\/s\)'
  - 'DISCONNECT_LOG \[In\] Disconnected from pool std'
  - "ERROR_LOG ERROR: Please check if the network is abnormal."
  - "TARGET_LOG Found a solution with target %{NUMBER:target_value}"

metrics:
  - type: gauge
    name: proof1m
    help: Proof rate for 1 minute
    match: "%{PROVER_LOG}"
    value: "{{.proof1m}}"

  - type: gauge
    name: proof5m
    help: Proof rate for 5 minutes
    match: "%{PROVER_LOG}"
    value: "{{.proof5m}}"

  - type: gauge
    name: proof30m
    help: Proof rate for 30 minutes
    match: "%{PROVER_LOG}"
    value: "{{.proof30m}}"

  - type: gauge
    name: proof60m
    help: Proof rate for 60 minutes
    match: "%{PROVER_LOG}"
    value: "{{.proof60m}}"

  - type: counter
    name: DISCONNECT_FROM_POOL
    help: Counter for disconnections from pool
    match: "%{DISCONNECT_LOG}"
    value: "1"

  - type: counter
    name: ERROR_NETWORK
    help: Counter for network error occurrences
    match: "%{ERROR_LOG}"
    value: "1"

  - type: counter
    name: FOUND_TARGET
    help: Counter for found solutions with targets
    match: "%{TARGET_LOG}"
    value: "1"

server:
  protocol: http
  port: 9144
