- name: Copy exporters.zip to /usr/local/
  copy:
    src: exporters.zip
    dest: /usr/local/exporters.zip
    force: yes

- name: Check Unzip
  shell: unzip | grep "version info"
  register: unzip_check
  changed_when: false
  failed_when: false

- name: Install Unzip
  when: unzip_check.rc != 0
  become: true
  apt:
    name:
      - unzip
    state: present
    update_cache: yes

- name: Unzip exporters.zip
  ansible.builtin.unarchive:
    src: /usr/local/exporters.zip
    dest: /usr/local/
    remote_src: yes

- name: Set execute permissions on directories and their contents
  command: chmod -R +x /usr/local/{{ item }}
  loop:
    - prometheus
    - alertmanager
    - grok_exporter
    - node_exporter
    - process-exporter
