- name: Ping site multiple times until successful
  shell: ping -c 1 -w 5 baidu.com
  register: ping_result
  until: ping_result.rc == 0
  retries: 5
  delay: 1

- name: Ping result
  debug:
    msg: "{{ ping_result.stdout_lines }}"
