- name: Download NVIDIA GPG key
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    dest: /tmp/nvidia-gpgkey
    mode: "1777"

- name: Check if NVIDIA GPG keyring exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  register: gpgkeyring

- name: Add NVIDIA GPG key to the keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia-gpgkey
  become: yes
  when: not gpgkeyring.stat.exists

- name: Download NVIDIA container toolkit list
  ansible.builtin.get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /tmp/nvidia-container-toolkit.list
    mode: "1777"

- name: Modify the container toolkit list to include the signed-by option
  ansible.builtin.command:
    cmd: sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' /tmp/nvidia-container-toolkit.list
  register: modified_list
  when: not gpgkeyring.stat.exists

- name: Check if container toolkit list exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  register: toolkitlist

- name: Save modified container toolkit list
  ansible.builtin.copy:
    content: "{{ modified_list.stdout }}"
    dest: /etc/apt/sources.list.d/nvidia-container-toolkit.list
    mode: "1777"
  become: yes
  when: not toolkitlist.stat.exists

- name: Install nvidia-docker2 and nvidia-container-toolkit
  become: true
  apt:
    name:
      - nvidia-docker2
      - nvidia-container-toolkit
    state: present
    update_cache: yes

- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
  become: true
