- name: Run dcgm-exporter Docker container
  community.docker.docker_container:
    name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter
    state: started
    restart_policy: absent
    detach: true
    remove: true
    gpus: all
    ports:
      - "9400:9400"