- name: 启动DCGM-Exporter
  community.docker.docker_container:
    name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter
    state: started
    detach: true
    auto_remove: true
    device_requests:
      - driver: nvidia
        count: -1
        capabilities: [[gpu]]
    ports:
      - "9400:9400"
    restart_policy: no